// =============================================================================
// VELVET PERFUMES - Fragrances Database
// Real compositions based on official notes and fragrance community data
// =============================================================================

export type Season = "spring" | "summer" | "fall" | "winter";
export type Gender = "men" | "women" | "unisex";
export type Occasion = "casual" | "formal" | "night-out" | "office" | "date" | "special";

export interface Ingredient {
    name: string;
    percentage: number; // 0-100 concentration/prominence
    category: "top" | "heart" | "base";
}

export interface Fragrance {
    id: string;
    slug: string;
    name: string;
    brandId: string;
    year: number;
    perfumer: string;
    price: number;
    sizes: { size: string; price: number }[];
    image: string;
    description: string;
    gender: Gender;
    seasons: Season[];
    occasions: Occasion[];
    temperature: "cold" | "warm" | "versatile";
    longevity: number; // 1-10 scale (hours approximation)
    sillage: number; // 1-10 scale
    ingredients: Ingredient[];
    isNew: boolean;
    isBestseller: boolean;
    rating: number;
    reviews: number;
}

// =============================================================================
// DIOR FRAGRANCES
// =============================================================================

const DIOR_FRAGRANCES: Fragrance[] = [
    {
        id: "dior-sauvage-edp",
        slug: "sauvage-edp",
        name: "Sauvage Eau de Parfum",
        brandId: "dior",
        year: 2018,
        perfumer: "François Demachy",
        price: 150,
        sizes: [
            { size: "60ml", price: 110 },
            { size: "100ml", price: 150 },
            { size: "200ml", price: 200 },
        ],
        image: "/images/velvet/fragrances/dior-sauvage-edp.png",
        description: "A powerfully fresh composition with a woody, ambroxan-rich trail. Bergamot from Calabria meets a blend of spices on a background of Papua New Guinean vanilla absolute.",
        gender: "men",
        seasons: ["fall", "winter", "spring"],
        occasions: ["casual", "office", "date"],
        temperature: "versatile",
        longevity: 8,
        sillage: 8,
        ingredients: [
            { name: "Bergamot", percentage: 85, category: "top" },
            { name: "Pepper", percentage: 60, category: "top" },
            { name: "Lavender", percentage: 70, category: "heart" },
            { name: "Sichuan Pepper", percentage: 50, category: "heart" },
            { name: "Ambroxan", percentage: 90, category: "base" },
            { name: "Vanilla", percentage: 55, category: "base" },
            { name: "Cedar", percentage: 45, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.8,
        reviews: 2847,
    },
    {
        id: "dior-sauvage-elixir",
        slug: "sauvage-elixir",
        name: "Sauvage Elixir",
        brandId: "dior",
        year: 2021,
        perfumer: "François Demachy",
        price: 195,
        sizes: [
            { size: "60ml", price: 195 },
            { size: "100ml", price: 250 },
        ],
        image: "/images/velvet/fragrances/dior-sauvage-elixir.png",
        description: "The most concentrated and intense Sauvage. Spicy richness of cinnamon and nutmeg wrapped in luxurious sandalwood and smoky licorice.",
        gender: "men",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "date", "special"],
        temperature: "cold",
        longevity: 10,
        sillage: 9,
        ingredients: [
            { name: "Grapefruit", percentage: 70, category: "top" },
            { name: "Cinnamon", percentage: 65, category: "top" },
            { name: "Cardamom", percentage: 55, category: "heart" },
            { name: "Lavender", percentage: 80, category: "heart" },
            { name: "Nutmeg", percentage: 60, category: "heart" },
            { name: "Sandalwood", percentage: 85, category: "base" },
            { name: "Licorice", percentage: 40, category: "base" },
            { name: "Amber", percentage: 75, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.9,
        reviews: 1523,
    },
    {
        id: "dior-homme-intense",
        slug: "dior-homme-intense",
        name: "Dior Homme Intense",
        brandId: "dior",
        year: 2011,
        perfumer: "François Demachy",
        price: 140,
        sizes: [
            { size: "50ml", price: 110 },
            { size: "100ml", price: 140 },
            { size: "150ml", price: 175 },
        ],
        image: "/images/velvet/fragrances/dior-homme-intense.png",
        description: "A sophisticated iris-driven fragrance with creamy amber and sensual musk. The quintessential modern gentleman's scent.",
        gender: "men",
        seasons: ["fall", "winter", "spring"],
        occasions: ["formal", "date", "office"],
        temperature: "cold",
        longevity: 7,
        sillage: 6,
        ingredients: [
            { name: "Lavender", percentage: 65, category: "top" },
            { name: "Iris", percentage: 95, category: "heart" },
            { name: "Ambrette", percentage: 50, category: "heart" },
            { name: "Virginia Cedar", percentage: 70, category: "base" },
            { name: "Vetiver", percentage: 55, category: "base" },
            { name: "Musk", percentage: 60, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.6,
        reviews: 892,
    },
    {
        id: "dior-miss-dior-edp",
        slug: "miss-dior-edp",
        name: "Miss Dior Eau de Parfum",
        brandId: "dior",
        year: 2021,
        perfumer: "François Demachy",
        price: 135,
        sizes: [
            { size: "30ml", price: 85 },
            { size: "50ml", price: 120 },
            { size: "100ml", price: 165 },
        ],
        image: "/images/velvet/fragrances/miss-dior-edp.png",
        description: "A fresh, floral fragrance celebrating the Grasse rose. Lily of the valley meets peony in a powdery, romantic composition.",
        gender: "women",
        seasons: ["spring", "summer", "fall"],
        occasions: ["casual", "date", "office"],
        temperature: "warm",
        longevity: 6,
        sillage: 5,
        ingredients: [
            { name: "Lily of the Valley", percentage: 80, category: "top" },
            { name: "Peony", percentage: 75, category: "heart" },
            { name: "Grasse Rose", percentage: 90, category: "heart" },
            { name: "Iris", percentage: 60, category: "heart" },
            { name: "Musk", percentage: 50, category: "base" },
            { name: "Rosewood", percentage: 45, category: "base" },
        ],
        isNew: true,
        isBestseller: true,
        rating: 4.7,
        reviews: 1654,
    },
    {
        id: "dior-jadore",
        slug: "jadore",
        name: "J'adore Eau de Parfum",
        brandId: "dior",
        year: 1999,
        perfumer: "Calice Becker",
        price: 145,
        sizes: [
            { size: "30ml", price: 90 },
            { size: "50ml", price: 125 },
            { size: "100ml", price: 170 },
        ],
        image: "/images/velvet/fragrances/dior-jadore.png",
        description: "The iconic feminine fragrance. A symphony of ylang-ylang, Damascus rose, and jasmine with a sensual fruity touch.",
        gender: "women",
        seasons: ["spring", "summer", "fall"],
        occasions: ["formal", "date", "special"],
        temperature: "warm",
        longevity: 7,
        sillage: 6,
        ingredients: [
            { name: "Ylang-Ylang", percentage: 85, category: "top" },
            { name: "Mandarin", percentage: 55, category: "top" },
            { name: "Jasmine", percentage: 90, category: "heart" },
            { name: "Damascus Rose", percentage: 85, category: "heart" },
            { name: "Tuberose", percentage: 60, category: "heart" },
            { name: "Blackberry Musk", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.5,
        reviews: 3241,
    },
    {
        id: "dior-fahrenheit",
        slug: "fahrenheit",
        name: "Fahrenheit",
        brandId: "dior",
        year: 1988,
        perfumer: "Jean-Louis Sieuzac",
        price: 120,
        sizes: [
            { size: "50ml", price: 95 },
            { size: "100ml", price: 130 },
            { size: "200ml", price: 175 },
        ],
        image: "/images/velvet/fragrances/dior-fahrenheit.png",
        description: "A revolutionary scent with petrol notes, violet leaf, and leather. Bold, masculine, and utterly unique since 1988.",
        gender: "men",
        seasons: ["fall", "winter"],
        occasions: ["casual", "night-out"],
        temperature: "cold",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Violet Leaf", percentage: 85, category: "top" },
            { name: "Hawthorn", percentage: 50, category: "top" },
            { name: "Nutmeg", percentage: 45, category: "heart" },
            { name: "Cedar", percentage: 70, category: "heart" },
            { name: "Leather", percentage: 80, category: "base" },
            { name: "Vetiver", percentage: 60, category: "base" },
            { name: "Musk", percentage: 55, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.4,
        reviews: 1876,
    },
    {
        id: "dior-poison-girl",
        slug: "poison-girl",
        name: "Poison Girl",
        brandId: "dior",
        year: 2016,
        perfumer: "François Demachy",
        price: 125,
        sizes: [
            { size: "30ml", price: 80 },
            { size: "50ml", price: 110 },
            { size: "100ml", price: 150 },
        ],
        image: "/images/velvet/fragrances/dior-poison-girl.png",
        description: "A bitter-sweet addiction. Orange blossom meets almond and vanilla in a playfully dark composition.",
        gender: "women",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "date"],
        temperature: "cold",
        longevity: 7,
        sillage: 6,
        ingredients: [
            { name: "Bitter Orange", percentage: 70, category: "top" },
            { name: "Lemon", percentage: 45, category: "top" },
            { name: "Damask Rose", percentage: 80, category: "heart" },
            { name: "Orange Blossom", percentage: 75, category: "heart" },
            { name: "Vanilla", percentage: 85, category: "base" },
            { name: "Tonka Bean", percentage: 70, category: "base" },
            { name: "Sandalwood", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.3,
        reviews: 743,
    },
    {
        id: "dior-oud-ispahan",
        slug: "oud-ispahan",
        name: "Oud Ispahan",
        brandId: "dior",
        year: 2012,
        perfumer: "François Demachy",
        price: 350,
        sizes: [
            { size: "40ml", price: 250 },
            { size: "125ml", price: 400 },
        ],
        image: "/images/velvet/fragrances/dior-oud-ispahan.jpg",
        description: "From the Privée collection. Precious oud meets the legendary Damask rose of Ispahan in an oriental masterpiece.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["special", "night-out", "formal"],
        temperature: "cold",
        longevity: 9,
        sillage: 8,
        ingredients: [
            { name: "Labdanum", percentage: 60, category: "top" },
            { name: "Damask Rose", percentage: 95, category: "heart" },
            { name: "Patchouli", percentage: 55, category: "heart" },
            { name: "Oud", percentage: 90, category: "base" },
            { name: "Sandalwood", percentage: 70, category: "base" },
            { name: "Amber", percentage: 65, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.7,
        reviews: 456,
    },
    {
        id: "dior-joy",
        slug: "joy",
        name: "JOY by Dior",
        brandId: "dior",
        year: 2018,
        perfumer: "François Demachy",
        price: 130,
        sizes: [
            { size: "30ml", price: 85 },
            { size: "50ml", price: 115 },
            { size: "90ml", price: 155 },
        ],
        image: "/images/velvet/fragrances/dior-joy.png",
        description: "A luminous floral with abundant flowers and creamy sandalwood. The fragrance of happiness.",
        gender: "women",
        seasons: ["spring", "summer"],
        occasions: ["casual", "office", "date"],
        temperature: "warm",
        longevity: 6,
        sillage: 5,
        ingredients: [
            { name: "Bergamot", percentage: 70, category: "top" },
            { name: "Mandarin", percentage: 55, category: "top" },
            { name: "Rose", percentage: 90, category: "heart" },
            { name: "Jasmine", percentage: 85, category: "heart" },
            { name: "Sandalwood", percentage: 80, category: "base" },
            { name: "Musk", percentage: 60, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.2,
        reviews: 567,
    },
    {
        id: "dior-homme-cologne",
        slug: "dior-homme-cologne",
        name: "Dior Homme Cologne",
        brandId: "dior",
        year: 2013,
        perfumer: "François Demachy",
        price: 115,
        sizes: [
            { size: "75ml", price: 100 },
            { size: "125ml", price: 130 },
        ],
        image: "/images/velvet/fragrances/dior-homme-cologne.png",
        description: "Ultra-fresh citrus cologne with white musk. Perfect for hot days and casual occasions.",
        gender: "men",
        seasons: ["spring", "summer"],
        occasions: ["casual", "office"],
        temperature: "warm",
        longevity: 4,
        sillage: 4,
        ingredients: [
            { name: "Bergamot", percentage: 90, category: "top" },
            { name: "Grapefruit", percentage: 75, category: "top" },
            { name: "Neroli", percentage: 65, category: "heart" },
            { name: "Orange Blossom", percentage: 60, category: "heart" },
            { name: "White Musk", percentage: 70, category: "base" },
            { name: "Vetiver", percentage: 40, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.1,
        reviews: 423,
    },
];

// =============================================================================
// CHANEL FRAGRANCES
// =============================================================================

const CHANEL_FRAGRANCES: Fragrance[] = [
    {
        id: "chanel-bleu-edp",
        slug: "bleu-de-chanel-edp",
        name: "Bleu de Chanel EDP",
        brandId: "chanel",
        year: 2014,
        perfumer: "Jacques Polge",
        price: 155,
        sizes: [
            { size: "50ml", price: 120 },
            { size: "100ml", price: 170 },
            { size: "150ml", price: 215 },
        ],
        image: "/images/velvet/fragrances/chanel-bleu-edp.jpg",
        description: "A woody, aromatic fragrance that embodies freedom. Citrus meets sandalwood and cedar in perfect harmony.",
        gender: "men",
        seasons: ["spring", "summer", "fall", "winter"],
        occasions: ["casual", "office", "date", "formal"],
        temperature: "versatile",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Grapefruit", percentage: 75, category: "top" },
            { name: "Lemon", percentage: 60, category: "top" },
            { name: "Mint", percentage: 50, category: "top" },
            { name: "Ginger", percentage: 55, category: "heart" },
            { name: "Jasmine", percentage: 45, category: "heart" },
            { name: "Iso E Super", percentage: 65, category: "heart" },
            { name: "Sandalwood", percentage: 80, category: "base" },
            { name: "Cedar", percentage: 70, category: "base" },
            { name: "Incense", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.7,
        reviews: 3456,
    },
    {
        id: "chanel-bleu-parfum",
        slug: "bleu-de-chanel-parfum",
        name: "Bleu de Chanel Parfum",
        brandId: "chanel",
        year: 2018,
        perfumer: "Olivier Polge",
        price: 185,
        sizes: [
            { size: "50ml", price: 150 },
            { size: "100ml", price: 210 },
            { size: "150ml", price: 270 },
        ],
        image: "/images/velvet/fragrances/chanel-bleu-parfum.png",
        description: "The purest expression of Bleu. Warm woods and honey-like notes create a deeper, more refined experience.",
        gender: "men",
        seasons: ["fall", "winter", "spring"],
        occasions: ["formal", "date", "special"],
        temperature: "versatile",
        longevity: 10,
        sillage: 8,
        ingredients: [
            { name: "Citrus", percentage: 60, category: "top" },
            { name: "Mint", percentage: 45, category: "top" },
            { name: "Lavender", percentage: 55, category: "heart" },
            { name: "Geranium", percentage: 50, category: "heart" },
            { name: "Sandalwood", percentage: 90, category: "base" },
            { name: "Cedar", percentage: 75, category: "base" },
            { name: "Tonka Bean", percentage: 60, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.8,
        reviews: 2134,
    },
    {
        id: "chanel-no5-edp",
        slug: "no5-edp",
        name: "N°5 Eau de Parfum",
        brandId: "chanel",
        year: 1921,
        perfumer: "Ernest Beaux",
        price: 165,
        sizes: [
            { size: "35ml", price: 110 },
            { size: "50ml", price: 145 },
            { size: "100ml", price: 195 },
        ],
        image: "/images/velvet/fragrances/chanel-no5.png",
        description: "The most legendary fragrance in history. A floral-aldehyde masterpiece that defined modern perfumery.",
        gender: "women",
        seasons: ["fall", "winter", "spring"],
        occasions: ["formal", "special", "date"],
        temperature: "cold",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Aldehydes", percentage: 85, category: "top" },
            { name: "Bergamot", percentage: 60, category: "top" },
            { name: "Ylang-Ylang", percentage: 70, category: "heart" },
            { name: "Jasmine", percentage: 90, category: "heart" },
            { name: "May Rose", percentage: 85, category: "heart" },
            { name: "Sandalwood", percentage: 70, category: "base" },
            { name: "Vetiver", percentage: 55, category: "base" },
            { name: "Vanilla", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.6,
        reviews: 4532,
    },
    {
        id: "chanel-coco-mademoiselle",
        slug: "coco-mademoiselle",
        name: "Coco Mademoiselle",
        brandId: "chanel",
        year: 2001,
        perfumer: "Jacques Polge",
        price: 145,
        sizes: [
            { size: "35ml", price: 100 },
            { size: "50ml", price: 130 },
            { size: "100ml", price: 175 },
        ],
        image: "/images/velvet/fragrances/chanel-coco-mademoiselle.png",
        description: "Fresh, youthful, and irresistibly feminine. Orange meets rose and patchouli in a modern classic.",
        gender: "women",
        seasons: ["spring", "summer", "fall"],
        occasions: ["casual", "office", "date"],
        temperature: "warm",
        longevity: 7,
        sillage: 6,
        ingredients: [
            { name: "Orange", percentage: 80, category: "top" },
            { name: "Bergamot", percentage: 65, category: "top" },
            { name: "Rose", percentage: 85, category: "heart" },
            { name: "Jasmine", percentage: 70, category: "heart" },
            { name: "Lychee", percentage: 55, category: "heart" },
            { name: "Patchouli", percentage: 75, category: "base" },
            { name: "Vetiver", percentage: 50, category: "base" },
            { name: "Vanilla", percentage: 60, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.7,
        reviews: 5123,
    },
    {
        id: "chanel-allure-homme-sport",
        slug: "allure-homme-sport",
        name: "Allure Homme Sport",
        brandId: "chanel",
        year: 2004,
        perfumer: "Jacques Polge",
        price: 130,
        sizes: [
            { size: "50ml", price: 105 },
            { size: "100ml", price: 145 },
            { size: "150ml", price: 185 },
        ],
        image: "/images/velvet/fragrances/chanel-allure-homme-sport.png",
        description: "Dynamic and energetic. Fresh citrus and aldehydes with a clean white musk finish.",
        gender: "men",
        seasons: ["spring", "summer"],
        occasions: ["casual", "office"],
        temperature: "warm",
        longevity: 6,
        sillage: 5,
        ingredients: [
            { name: "Blood Orange", percentage: 85, category: "top" },
            { name: "Aldehydes", percentage: 60, category: "top" },
            { name: "Neroli", percentage: 55, category: "heart" },
            { name: "Cedar", percentage: 65, category: "heart" },
            { name: "White Musk", percentage: 75, category: "base" },
            { name: "Tonka Bean", percentage: 50, category: "base" },
            { name: "Amber", percentage: 45, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.4,
        reviews: 1876,
    },
    {
        id: "chanel-chance-eau-tendre",
        slug: "chance-eau-tendre",
        name: "Chance Eau Tendre",
        brandId: "chanel",
        year: 2010,
        perfumer: "Jacques Polge",
        price: 140,
        sizes: [
            { size: "35ml", price: 95 },
            { size: "50ml", price: 125 },
            { size: "100ml", price: 165 },
        ],
        image: "/images/velvet/fragrances/chanel-chance-eau-tendre.png",
        description: "A tender, sparkling floral. Grapefruit and quince meet jasmine in a soft, romantic composition.",
        gender: "women",
        seasons: ["spring", "summer"],
        occasions: ["casual", "date"],
        temperature: "warm",
        longevity: 5,
        sillage: 5,
        ingredients: [
            { name: "Grapefruit", percentage: 80, category: "top" },
            { name: "Quince", percentage: 70, category: "top" },
            { name: "Jasmine", percentage: 75, category: "heart" },
            { name: "Hyacinth", percentage: 55, category: "heart" },
            { name: "Cedar", percentage: 50, category: "base" },
            { name: "White Musk", percentage: 65, category: "base" },
            { name: "Amber", percentage: 45, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.5,
        reviews: 2345,
    },
    {
        id: "chanel-gabrielle",
        slug: "gabrielle",
        name: "Gabrielle Chanel",
        brandId: "chanel",
        year: 2017,
        perfumer: "Olivier Polge",
        price: 155,
        sizes: [
            { size: "35ml", price: 105 },
            { size: "50ml", price: 135 },
            { size: "100ml", price: 180 },
        ],
        image: "/images/velvet/fragrances/chanel-gabrielle.png",
        description: "A radiant solar flower. Four white flowers—jasmine, ylang-ylang, orange blossom, and tuberose—in luminous harmony.",
        gender: "women",
        seasons: ["spring", "summer", "fall"],
        occasions: ["casual", "office", "date"],
        temperature: "warm",
        longevity: 7,
        sillage: 6,
        ingredients: [
            { name: "Mandarin", percentage: 55, category: "top" },
            { name: "Grapefruit", percentage: 50, category: "top" },
            { name: "Orange Blossom", percentage: 85, category: "heart" },
            { name: "Jasmine", percentage: 90, category: "heart" },
            { name: "Ylang-Ylang", percentage: 75, category: "heart" },
            { name: "Tuberose", percentage: 80, category: "heart" },
            { name: "Sandalwood", percentage: 60, category: "base" },
            { name: "Musk", percentage: 55, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.3,
        reviews: 987,
    },
    {
        id: "chanel-platinum-egoiste",
        slug: "platinum-egoiste",
        name: "Égoïste Platinum",
        brandId: "chanel",
        year: 1993,
        perfumer: "Jacques Polge",
        price: 125,
        sizes: [
            { size: "50ml", price: 100 },
            { size: "100ml", price: 140 },
        ],
        image: "/images/velvet/fragrances/chanel-platinum-egoiste.jpg",
        description: "A classic fougère with modern freshness. Lavender and rosemary over cedar and oakmoss.",
        gender: "men",
        seasons: ["spring", "summer", "fall"],
        occasions: ["office", "casual"],
        temperature: "versatile",
        longevity: 6,
        sillage: 5,
        ingredients: [
            { name: "Lavender", percentage: 85, category: "top" },
            { name: "Rosemary", percentage: 70, category: "top" },
            { name: "Geranium", percentage: 55, category: "heart" },
            { name: "Galbanum", percentage: 50, category: "heart" },
            { name: "Oakmoss", percentage: 65, category: "base" },
            { name: "Cedar", percentage: 60, category: "base" },
            { name: "Sandalwood", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.2,
        reviews: 1234,
    },
    {
        id: "chanel-antaeus",
        slug: "antaeus",
        name: "Antaeus",
        brandId: "chanel",
        year: 1981,
        perfumer: "Jacques Polge",
        price: 120,
        sizes: [
            { size: "50ml", price: 95 },
            { size: "100ml", price: 135 },
        ],
        image: "/images/velvet/fragrances/chanel-antaeus.jpg",
        description: "A powerful, masculine chypre. Sage and labdanum with castoreum and oakmoss. For the confident man.",
        gender: "men",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "formal"],
        temperature: "cold",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Clary Sage", percentage: 75, category: "top" },
            { name: "Coriander", percentage: 60, category: "top" },
            { name: "Labdanum", percentage: 80, category: "heart" },
            { name: "Patchouli", percentage: 70, category: "heart" },
            { name: "Oakmoss", percentage: 85, category: "base" },
            { name: "Castoreum", percentage: 55, category: "base" },
            { name: "Leather", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.4,
        reviews: 654,
    },
    {
        id: "chanel-les-exclusifs-sycomore",
        slug: "sycomore",
        name: "Les Exclusifs: Sycomore",
        brandId: "chanel",
        year: 2008,
        perfumer: "Jacques Polge",
        price: 350,
        sizes: [
            { size: "75ml", price: 280 },
            { size: "200ml", price: 420 },
        ],
        image: "/images/velvet/fragrances/chanel-sycomore.jpg",
        description: "From the exclusive collection. A forest of vetiver and cypress with smoky incense. Meditation in a bottle.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["special", "formal"],
        temperature: "cold",
        longevity: 9,
        sillage: 7,
        ingredients: [
            { name: "Pink Pepper", percentage: 55, category: "top" },
            { name: "Juniper", percentage: 50, category: "top" },
            { name: "Vetiver", percentage: 95, category: "heart" },
            { name: "Cypress", percentage: 75, category: "heart" },
            { name: "Sandalwood", percentage: 70, category: "base" },
            { name: "Amber", percentage: 60, category: "base" },
            { name: "Incense", percentage: 55, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.8,
        reviews: 312,
    },
];

// =============================================================================
// TOM FORD FRAGRANCES
// =============================================================================

const TOM_FORD_FRAGRANCES: Fragrance[] = [
    {
        id: "tf-oud-wood",
        slug: "oud-wood",
        name: "Oud Wood",
        brandId: "tom-ford",
        year: 2007,
        perfumer: "Richard Herpin",
        price: 280,
        sizes: [
            { size: "30ml", price: 195 },
            { size: "50ml", price: 280 },
            { size: "100ml", price: 395 },
        ],
        image: "/images/velvet/fragrances/tf-oud-wood.png",
        description: "The signature Tom Ford oud. Rare oud wood meets sandalwood and vetiver in a sophisticated, smoky composition.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["formal", "night-out", "special"],
        temperature: "cold",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Rosewood", percentage: 65, category: "top" },
            { name: "Cardamom", percentage: 55, category: "top" },
            { name: "Oud", percentage: 90, category: "heart" },
            { name: "Sandalwood", percentage: 85, category: "heart" },
            { name: "Vetiver", percentage: 70, category: "base" },
            { name: "Tonka Bean", percentage: 55, category: "base" },
            { name: "Amber", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.8,
        reviews: 2876,
    },
    {
        id: "tf-tobacco-vanille",
        slug: "tobacco-vanille",
        name: "Tobacco Vanille",
        brandId: "tom-ford",
        year: 2007,
        perfumer: "Olivier Gillotin",
        price: 285,
        sizes: [
            { size: "30ml", price: 200 },
            { size: "50ml", price: 285 },
            { size: "100ml", price: 400 },
        ],
        image: "/images/velvet/fragrances/tf-tobacco-vanille.png",
        description: "Opulent and warm. Tobacco leaf meets vanilla, cacao, and dried fruits in a decadent embrace.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "date", "special"],
        temperature: "cold",
        longevity: 10,
        sillage: 9,
        ingredients: [
            { name: "Tobacco Leaf", percentage: 90, category: "top" },
            { name: "Spices", percentage: 60, category: "top" },
            { name: "Vanilla", percentage: 95, category: "heart" },
            { name: "Cacao", percentage: 70, category: "heart" },
            { name: "Tonka Bean", percentage: 80, category: "base" },
            { name: "Dried Fruits", percentage: 55, category: "base" },
            { name: "Woods", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.9,
        reviews: 3124,
    },
    {
        id: "tf-black-orchid",
        slug: "black-orchid",
        name: "Black Orchid",
        brandId: "tom-ford",
        year: 2006,
        perfumer: "David Apel",
        price: 170,
        sizes: [
            { size: "30ml", price: 120 },
            { size: "50ml", price: 170 },
            { size: "100ml", price: 235 },
        ],
        image: "/images/velvet/fragrances/tf-black-orchid.png",
        description: "Dark, sensual, and intoxicating. Black truffle meets ylang-ylang in a mysterious, luxurious blend.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "date", "special"],
        temperature: "cold",
        longevity: 9,
        sillage: 8,
        ingredients: [
            { name: "Black Truffle", percentage: 75, category: "top" },
            { name: "Bergamot", percentage: 55, category: "top" },
            { name: "Ylang-Ylang", percentage: 85, category: "heart" },
            { name: "Orchid", percentage: 90, category: "heart" },
            { name: "Patchouli", percentage: 80, category: "base" },
            { name: "Incense", percentage: 65, category: "base" },
            { name: "Vanilla", percentage: 70, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.6,
        reviews: 4231,
    },
    {
        id: "tf-lost-cherry",
        slug: "lost-cherry",
        name: "Lost Cherry",
        brandId: "tom-ford",
        year: 2018,
        perfumer: "Louise Turner",
        price: 350,
        sizes: [
            { size: "30ml", price: 245 },
            { size: "50ml", price: 350 },
            { size: "100ml", price: 495 },
        ],
        image: "/images/velvet/fragrances/tf-lost-cherry.jpg",
        description: "Provocatively playful. Black cherry meets almond and Turkish rose in a gourmand temptation.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["date", "night-out", "special"],
        temperature: "cold",
        longevity: 8,
        sillage: 8,
        ingredients: [
            { name: "Black Cherry", percentage: 95, category: "top" },
            { name: "Bitter Almond", percentage: 75, category: "top" },
            { name: "Griotte Syrup", percentage: 65, category: "heart" },
            { name: "Turkish Rose", percentage: 70, category: "heart" },
            { name: "Jasmine Sambac", percentage: 55, category: "heart" },
            { name: "Peru Balsam", percentage: 60, category: "base" },
            { name: "Tonka Bean", percentage: 70, category: "base" },
            { name: "Sandalwood", percentage: 55, category: "base" },
            { name: "Cedar", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.7,
        reviews: 1876,
    },
    {
        id: "tf-noir-extreme",
        slug: "noir-extreme",
        name: "Noir Extreme",
        brandId: "tom-ford",
        year: 2015,
        perfumer: "Olivier Gillotin",
        price: 165,
        sizes: [
            { size: "50ml", price: 140 },
            { size: "100ml", price: 195 },
        ],
        image: "/images/velvet/fragrances/tf-noir-extreme.jpg",
        description: "Oriental amber with spicy warmth. Cardamom and nutmeg wrapped in a seductive vanilla finish.",
        gender: "men",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "date", "formal"],
        temperature: "cold",
        longevity: 9,
        sillage: 8,
        ingredients: [
            { name: "Cardamom", percentage: 80, category: "top" },
            { name: "Nutmeg", percentage: 65, category: "top" },
            { name: "Saffron", percentage: 55, category: "heart" },
            { name: "Rose Absolute", percentage: 60, category: "heart" },
            { name: "Vanilla", percentage: 85, category: "base" },
            { name: "Amber Woods", percentage: 75, category: "base" },
            { name: "Sandalwood", percentage: 70, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.5,
        reviews: 1432,
    },
    {
        id: "tf-tuscan-leather",
        slug: "tuscan-leather",
        name: "Tuscan Leather",
        brandId: "tom-ford",
        year: 2007,
        perfumer: "Rodrigo Flores-Roux",
        price: 290,
        sizes: [
            { size: "30ml", price: 200 },
            { size: "50ml", price: 290 },
            { size: "100ml", price: 405 },
        ],
        image: "/images/velvet/fragrances/tf-tuscan-leather.jpg",
        description: "Raw, animalic, and powerful. Italian leather meets saffron and raspberry in a bold statement.",
        gender: "unisex",
        seasons: ["fall", "winter"],
        occasions: ["night-out", "formal", "special"],
        temperature: "cold",
        longevity: 10,
        sillage: 9,
        ingredients: [
            { name: "Saffron", percentage: 70, category: "top" },
            { name: "Raspberry", percentage: 65, category: "top" },
            { name: "Leather", percentage: 95, category: "heart" },
            { name: "Olibanum", percentage: 60, category: "heart" },
            { name: "Thyme", percentage: 45, category: "heart" },
            { name: "Amber", percentage: 70, category: "base" },
            { name: "Jasmine", percentage: 55, category: "base" },
            { name: "Woods", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.7,
        reviews: 1654,
    },
    {
        id: "tf-bitter-peach",
        slug: "bitter-peach",
        name: "Bitter Peach",
        brandId: "tom-ford",
        year: 2020,
        perfumer: "Louise Turner",
        price: 355,
        sizes: [
            { size: "30ml", price: 250 },
            { size: "50ml", price: 355 },
            { size: "100ml", price: 500 },
        ],
        image: "/images/velvet/fragrances/tf-bitter-peach.jpg",
        description: "Sinfully juicy. Succulent peach with blood orange and a heady rum finish. Pure temptation.",
        gender: "unisex",
        seasons: ["fall", "winter", "spring"],
        occasions: ["date", "night-out", "special"],
        temperature: "versatile",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Peach", percentage: 95, category: "top" },
            { name: "Blood Orange", percentage: 70, category: "top" },
            { name: "Cardamom", percentage: 55, category: "heart" },
            { name: "Rum", percentage: 65, category: "heart" },
            { name: "Davana", percentage: 50, category: "heart" },
            { name: "Sandalwood", percentage: 60, category: "base" },
            { name: "Cashmeran", percentage: 55, category: "base" },
            { name: "Vanilla", percentage: 70, category: "base" },
        ],
        isNew: true,
        isBestseller: false,
        rating: 4.4,
        reviews: 876,
    },
    {
        id: "tf-neroli-portofino",
        slug: "neroli-portofino",
        name: "Neroli Portofino",
        brandId: "tom-ford",
        year: 2011,
        perfumer: "Harry Fremont",
        price: 265,
        sizes: [
            { size: "30ml", price: 185 },
            { size: "50ml", price: 265 },
            { size: "100ml", price: 370 },
        ],
        image: "/images/velvet/fragrances/tf-neroli-portofino.jpg",
        description: "The Italian Riviera in a bottle. Sparkling citrus and neroli with Mediterranean amber.",
        gender: "unisex",
        seasons: ["spring", "summer"],
        occasions: ["casual", "office", "date"],
        temperature: "warm",
        longevity: 5,
        sillage: 5,
        ingredients: [
            { name: "Bergamot", percentage: 85, category: "top" },
            { name: "Mandarin", percentage: 70, category: "top" },
            { name: "Lemon", percentage: 75, category: "top" },
            { name: "Neroli", percentage: 90, category: "heart" },
            { name: "Orange Flower", percentage: 80, category: "heart" },
            { name: "Amber", percentage: 55, category: "base" },
            { name: "Musk", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.5,
        reviews: 1987,
    },
    {
        id: "tf-ombre-leather",
        slug: "ombre-leather",
        name: "Ombré Leather",
        brandId: "tom-ford",
        year: 2018,
        perfumer: "Sonia Constant",
        price: 170,
        sizes: [
            { size: "50ml", price: 150 },
            { size: "100ml", price: 200 },
        ],
        image: "/images/velvet/fragrances/tf-ombre-leather.jpg",
        description: "A modernized leather for everyday luxury. Cardamom and jasmine soften bold leather notes.",
        gender: "unisex",
        seasons: ["fall", "winter", "spring"],
        occasions: ["casual", "office", "date"],
        temperature: "versatile",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Cardamom", percentage: 70, category: "top" },
            { name: "Leather", percentage: 90, category: "heart" },
            { name: "Jasmine Sambac", percentage: 60, category: "heart" },
            { name: "Patchouli", percentage: 65, category: "base" },
            { name: "Amber", percentage: 70, category: "base" },
            { name: "Moss", percentage: 55, category: "base" },
        ],
        isNew: false,
        isBestseller: true,
        rating: 4.6,
        reviews: 1543,
    },
    {
        id: "tf-fucking-fabulous",
        slug: "fucking-fabulous",
        name: "F*cking Fabulous",
        brandId: "tom-ford",
        year: 2017,
        perfumer: "Givaudan",
        price: 375,
        sizes: [
            { size: "50ml", price: 310 },
            { size: "100ml", price: 445 },
        ],
        image: "/images/velvet/fragrances/tf-f-fabulous.jpg",
        description: "Unapologetically bold. Lavender meets leather and almond in an audacious, confident statement.",
        gender: "unisex",
        seasons: ["fall", "winter", "spring"],
        occasions: ["night-out", "special"],
        temperature: "versatile",
        longevity: 8,
        sillage: 7,
        ingredients: [
            { name: "Lavender", percentage: 80, category: "top" },
            { name: "Bitter Almond", percentage: 65, category: "heart" },
            { name: "Leather", percentage: 75, category: "heart" },
            { name: "Vanilla", percentage: 70, category: "base" },
            { name: "Orris", percentage: 60, category: "base" },
            { name: "Tonka Bean", percentage: 55, category: "base" },
            { name: "Cashmeran", percentage: 50, category: "base" },
        ],
        isNew: false,
        isBestseller: false,
        rating: 4.3,
        reviews: 1234,
    },
];

// =============================================================================
// ALL FRAGRANCES
// =============================================================================

export const FRAGRANCES: Fragrance[] = [
    ...DIOR_FRAGRANCES,
    ...CHANEL_FRAGRANCES,
    ...TOM_FORD_FRAGRANCES,
];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export const getFragranceBySlug = (slug: string): Fragrance | undefined => {
    return FRAGRANCES.find((f) => f.slug === slug);
};

export const getFragrancesByBrand = (brandId: string): Fragrance[] => {
    return FRAGRANCES.filter((f) => f.brandId === brandId);
};

export const getFragrancesByGender = (gender: Gender): Fragrance[] => {
    return FRAGRANCES.filter((f) => f.gender === gender);
};

export const getFragrancesBySeason = (season: Season): Fragrance[] => {
    return FRAGRANCES.filter((f) => f.seasons.includes(season));
};

export const getBestsellers = (): Fragrance[] => {
    return FRAGRANCES.filter((f) => f.isBestseller).slice(0, 10);
};

export const getNewArrivals = (): Fragrance[] => {
    return FRAGRANCES.filter((f) => f.isNew);
};

// Get all unique ingredients across all fragrances
export const getAllIngredients = (): string[] => {
    const ingredientSet = new Set<string>();
    FRAGRANCES.forEach((f) => {
        f.ingredients.forEach((i) => ingredientSet.add(i.name));
    });
    return Array.from(ingredientSet).sort();
};
